package com.dyrnq.httpbin.component;

import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

/**
 * Reactive (WebFlux) port of the servlet
 * {@code com.dyrnq.httpbin.component.HttpMethodsService}.
 *
 * <p>All HTTP-verb endpoints ({@code GET/POST/PUT/PATCH/DELETE /get|...})
 * return the mirror response generated by
 * {@link ReactiveBaseService#anything(ServerWebExchange)}.
 */
@Component
public class HttpMethodsService extends ReactiveBaseService {

    /**
     * Reactive equivalent of
     * {@code super.anything(null)} — the {@code /get} / {@code /post}
     * etc. endpoints all delegate to {@code BaseService.anything()}.
     */
    public Mono<Void> httpMethods(ServerWebExchange exchange) {
        return super.anything(exchange);
    }
}
