name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    paths:
      - "common/**"
      - "springboot-httpbin/**"
      - "springboot-httpbin-reactive/**"
      - "build.sh"
      - "pom.xml"
      - "docker/**"
  #pull_request:
    #branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4 # v4

    -
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    -
      name: Java Environment
      run: env | grep '^JAVA'

    -
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # -
    #   name: Configure git
    #   run: |
    #     git config --global committer.email "dyrnq@qq.com"
    #     git config --global committer.name "dyrnq"
    #     git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
    #     git config --global author.name "${GITHUB_ACTOR}"

    # -
    #   name: Checkout main branch
    #   run: |
    #     git branch -a 
    #     git checkout main


    -
      name: Build with Maven
      run: ./build.sh

    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Build dockerfile (with no push)
      run: |
        
        for line in  "eclipse-temurin:21.0.4_7-jdk-noble" "eclipse-temurin:21.0.4_7-jre-noble"; do
          tag=""
          if grep -q jre <<< "${line}"; then   tag="${tag} --tag ${{ secrets.DOCKER_USERNAME }}/springboot-httpbin:jre-latest"; fi;
          if grep -q jdk <<< "${line}"; then   tag="${tag} --tag ${{ secrets.DOCKER_USERNAME }}/springboot-httpbin:jdk-latest"; fi;
          if grep -q jre <<< "${line}"; then   tag="${tag} --tag ${{ secrets.DOCKER_USERNAME }}/springboot-httpbin:latest"; fi;
          echo $tag;
          docker buildx build \
          --build-arg BASE_IMAGE="${line}" \
          --platform linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile . ${tag}
        done

    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build dockerfile (with push)
      run: |
        for line in  "eclipse-temurin:21.0.4_7-jdk-noble" "eclipse-temurin:21.0.4_7-jre-noble"; do
          tag=""
          if grep -q jre <<< "${line}"; then   tag="${tag} --tag ${{ secrets.DOCKER_USERNAME }}/springboot-httpbin:jre-latest"; fi;
          if grep -q jdk <<< "${line}"; then   tag="${tag} --tag ${{ secrets.DOCKER_USERNAME }}/springboot-httpbin:jdk-latest"; fi;
          if grep -q jre <<< "${line}"; then   tag="${tag} --tag ${{ secrets.DOCKER_USERNAME }}/springboot-httpbin:latest"; fi;
          echo $tag;
          docker buildx build \
          --build-arg BASE_IMAGE="${line}" \
          --platform linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x \
          --output "type=image,push=true" \
          --file ./docker/Dockerfile . ${tag}
        done

