# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Test version
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
          echo ${{ github.ref }}

      -
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      -
        name: Java Environment
        run: env | grep '^JAVA'

      -
        name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2


      -
        name: Build with Maven
        run: ./build.sh
      -
        name: Gen sha256sum
        run: |
          sha256sum target/springboot-httpbin-jetty.jar     > target/springboot-httpbin-jetty.jar.sha256sum
          sha256sum target/springboot-httpbin-reactive.jar  > target/springboot-httpbin-reactive.jar.sha256sum
          sha256sum target/springboot-httpbin-tomcat.jar    > target/springboot-httpbin-tomcat.jar.sha256sum
          sha256sum target/springboot-httpbin-undertow.jar  > target/springboot-httpbin-undertow.jar.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            Release JvmOptionsParser ${{ steps.get_version.outputs.VERSION }}.
            - https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-jetty.jar    ([checksum](https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-jetty.jar.sha256sum))
            - https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-reactive.jar ([checksum](https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-reactive.jar.sha256sum))
            - https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-tomcat.jar   ([checksum](https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-tomcat.jar.sha256sum))
            - https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-undertow.jar ([checksum](https://github.com/dyrnq/springboot-httpbin/releases/download/${{ steps.get_version.outputs.VERSION }}/springboot-httpbin-undertow.jar.sha256sum))

          files: |
            target/springboot-httpbin-jetty.jar
            target/springboot-httpbin-reactive.jar
            target/springboot-httpbin-tomcat.jar
            target/springboot-httpbin-undertow.jar
            target/springboot-httpbin-jetty.jar.sha256sum
            target/springboot-httpbin-reactive.jar.sha256sum
            target/springboot-httpbin-tomcat.jar.sha256sum
            target/springboot-httpbin-undertow.jar.sha256sum